CREATE TABLE IF NOT EXISTS `user` (
  `id` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(32) NOT NULL,
  `phone` VARCHAR(15) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL COMMENT '姓名',
  `age` INT(11) NULL DEFAULT NULL COMMENT '年龄',
  `sex` TINYINT(4) NULL DEFAULT NULL COMMENT '0 - 男，1 - 女',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;