spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
        - id: sso
          uri: lb://sso
          predicates:
            - Path=/sso/**
    nacos:
      discovery:
        server-addr: org.local.com:8848