spring:
  application:
    name: gateway
    nacos:
      discovery:
        server-addr: org.local.com:8848
  cloud:
    gateway:
      routes:
        - id: auth-server
          uri: lb://auth-server
          predicates:
            - Path=/auth/**
