server:
  port: 8201
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: demo-auth
          uri: lb://demo-auth
          predicates:
            - Path=/demo-auth/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8201/demo-auth/rsa/publicKey'
  redis:
    cluster:
      nodes: 192.168.30.201:7000,192.168.30.201:7001,192.168.30.201:7010,192.168.30.201:7011,192.168.30.201:7020,192.168.30.201:7021
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
secure:
  ignore:
    urls:
      - "/demo-auth/oauth/token"
      - "/demo-auth/rsa/publicKey"
      - "/demo-auth/user/register"
      - "/demo-auth/user/login"
