spring:
  application:
    name: sso
  lifecycle:
    timeout-per-shutdown-phase: 15s # kill程序后15s后再停止程序，此过程中不会接收新的请求
  jackson:
    default-property-inclusion: non_null
  cloud:
    nacos:
      discovery:
        server-addr: org.local.com:8848
server:
  port: 17000
  servlet:
    context-path: /sso
  shutdown: graceful # graceful优雅的关机， immediate 立即停止
management:
  endpoint:
    health:
      show-details: always