spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://org.local.com:3306/db_user?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123123
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        enable_lazy_load_no_trans: true
  lifecycle:
    timeout-per-shutdown-phase: 15s # kill程序后15s后再停止程序，此过程中不会接收新的请求
  jackson:
    default-property-inclusion: non_null
  cloud:
    nacos:
      discovery:
        server-addr: org.local.com:8848
server:
  port: 18000
  servlet:
    context-path: /user
  shutdown: graceful # graceful优雅的关机， immediate 立即停止
management:
  endpoint:
    health:
      show-details: always
