spring:
  application:
    name: mall
  lifecycle:
    timeout-per-shutdown-phase: 15s # 配合server.shutdown: graceful延迟15秒停止服务
  datasource:
    url: jdbc:mysql://192.168.30.61:3306/db_mall?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1qaz1qaz
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: validate
server:
  port: 18888
  shutdown: graceful  # graceful优雅的，immediate 马上
